name: Deploy to GitHub Pages

on:
  push:
<<<<<<< HEAD
    branches: [ main ]
=======
    branches: [ master ]  # Use 'master' if that's your main branch
>>>>>>> c78b0ca096bd121fb89428fad56e0f4ad4756117

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          
      - name: Install dependencies
        run: npm install
      
      - name: Build with environment variables
        run: npm run build
        env:
          VITE_API_KEY: ${{ secrets.VITE_API_KEY }}
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
<<<<<<< HEAD
          keep_files: true
=======
>>>>>>> c78b0ca096bd121fb89428fad56e0f4ad4756117
